#
# NODE_ENV === production
#

app:
  title: 'Console'
  website: 'https://dxos.org'
  debug: "dxos:dashboard:*"
  theme: 'dark'

# Client routes (for Apache/NGINX proxy).
routes:
  wns:
    graphql: '/graphql'
  ipfs:
    graphql: '/webui'

# DxOS services.
services:
  wns:
    endpoint: 'https://node1.dxos.network/wns/graphql'

  signal:
    server: 'http://127.0.0.1:4000'

  ipfs:
    server: '/ip4/127.0.0.1/tcp/5001'
    gateway: 'http://127.0.0.1:8888/ipfs/'
    webui: 'http://127.0.0.1:5001/webui'
