#
# Config
#

title: 'Dashboard'

website: 'https://dxos.org'

# Client routes (for NGINX proxy).
routes:
  wns:
    port: 9473
    graphql: '/graphql'

services:

  ipfs:
    console: 'http://127.0.0.1:5001/webui'
    server: '/ip4/127.0.0.1/tcp/5001'

  signal:
    server: 'http://127.0.0.1:4000'

  wns:
#    endpoint: 'http://127.0.0.1:9473/graphql'
    endpoint: 'https://wns-testnet.dev.wireline.ninja/graphql'
