#
# NODE_ENV === development
#

services:
  app:
    server: 'http://127.0.0.1:6000'

  wns:
    server: 'http://127.0.0.1:9473/api'
    webui: 'http://127.0.0.1:9473/webui'

  signal:
    server: 'http://127.0.0.1:4000'
    api: 'http://127.0.0.1:4000'

  ipfs:
    server: '/ip4/127.0.0.1/tcp/5001'
    gateway: '/ip4//127.0.0.1:8888/ipfs/'
    webui: 'http://127.0.0.1:5001/webui'

  wellknown:
    endpoint: 'http://127.0.0.1:9000/.well-known/dxos'
