#
# NODE_ENV === production
# NOTE: Set CONFIG_FILE to swap out this config file.
#

services:
  app:
    server: 'http://127.0.0.1:5999'                             # TODO(burdon): ???

  wns:
    server: 'http://127.0.0.1:9473/api'
    webui: 'http://127.0.0.1:9473/webui'

  signal:
    server: 'http://127.0.0.1:4000'
    api: 'http://127.0.0.1:4000'                                # TODO(burdon): ???

  ipfs:
    server: '/ip4/127.0.0.1/tcp/5001'
    gateway: '/ip4//127.0.0.1:8888/ipfs/'
    webui: 'http://127.0.0.1:5001/webui'

  wellknown:
    endpoint: 'http://127.0.0.1:9000/.well-known/dxos'

routes:
  app:
    server: '/wrn'

  wns:
    server: '/dxos/wns/graphql'                                 # TODO(burdon): ???
    webui: '/dxos/wns/console'                                  # TODO(burdon): ???

  signal:
    api: '/dxos/signal/status'

  ipfs:
    server: '/dxos/ipfs/api'
    webui: '/dxos/ipfs/webui'

  wellknown:
    endpoint: '/.well-known/dxos'
