#
# DxOS services.
#

scripts:
  status:
    command: wire
    attributes:
      - 'services'
      - 'status'
      - '<name>'
  stop:
    command: wire
    attributes:
      - 'services'
      - 'stop'
      - '<name>'
  restart:
    command: wire
    attributes:
      - 'services'
      - 'restart'
      - '<name>'
  logs:
    command: wire
    attributes:
      - 'services'
      - 'logs'
      - '<name>'

services:
  wns-lite:
    log: '/var/log/wns-lite.log'
    scripts:
      start:
        command: wire
        attributes:
          - 'wns'
          - 'start'
          - '--lite'
          - '--daemon'
          - '--log-file'
          - '<logFile>'
          - '--node'
          - 'tcp://node1.dxos.network:26657'
          - '--reset'
          - '--'
          - '--gql-port'
          - '9473'
          - '--gql-playground-api-base'
          - '/dxos/wns'
          - '--endpoint'
          - 'http://127.0.0.1:9473/api'
        match: 'Syncing from'
      logs:
        command: wire
        attributes:
          - 'services'
          - 'logs'
          - '<name>'
          - '--log-file'
          - '<logFile>'
  ipfs:
    log: '/var/log/ipfs.log'
    scripts:
      start:
        command: wire
        attributes:
          - 'ipfs'
          - 'start'
          - '--daemon'
          - '--log-file'
          - '<logFile>'
      stop:
        command: wire
        attributes:
          - 'ipfs'
          - 'stop'
  app-server:
    log: '/var/log/app-server.log'
    scripts:
      start:
        command: wire
        attributes:
          - 'app'
          - 'serve'
          - '--daemon'
          - '--port'
          - 5999
          - '--log-file'
          - '<logFile>'
  signal:
    log: '/var/log/signal.log'
    scripts:
      start:
        command: wire
        attributes:
          - 'signal'
          - 'start'
          - '--daemon'
          - '--asBootstrap'
          - '--log-file'
          - '<logFile>'
        match: 'SIGNAL_PROTOCOL_TOPIC'
  bot-factory:
    log: '/var/log/bot-factory.log'
    scripts:
      start:
        command: wire
        attributes:
          - 'bot'
          - 'factory'
          - 'start'
          - '--daemon'
          - '--log-file'
          - '<logFile>'
        match: 'bot-factory'
      status:
        command: wire
        attributes:
          - 'bot'
          - 'factory'
          - 'status'
