#
# DxOS services.
#

scripts:
  status:
    command: wire
    attributes:
      - 'services'
      - 'status'
      - '<name>'
  stop:
    command: wire
    attributes:
      - 'services'
      - 'stop'
      - '<name>'
  restart:
    command: wire
    attributes:
      - 'services'
      - 'restart'
      - '<name>'
  logs:
    command: wire
    attributes:
      - 'services'
      - 'logs'
      - '<name>'

services:
  wns:
    log: '/tmp/wns.log'
    scripts:
      start:
        command: wire
        attributes:
          - 'wns'
          - 'start'
        # - '--lite'
          - '--daemon'
        # - '--procName'
        # - '<name>'
        match: 'Executed block'
      status:
        command: wire
        attributes:
          - 'wns'
          - 'status'
  ipfs:
    log: '/tmp/ipfs.log'
    scripts:
      start:
        command: wire
        attributes:
          - 'ipfs'
          - 'start'
          - '--daemon'
  app-serve:
    scripts:
      start:
        command: wire
        attributes:
          - 'app'
          - 'serve'
