#
# DxOS services.
#

scripts:
  status:
    command: wire
    attributes:
      - 'services'
      - 'status'
      - '<name>'
  stop:
    command: wire
    attributes:
      - 'services'
      - 'stop'
      - '<name>'
  restart:
    command: wire
    attributes:
      - 'services'
      - 'restart'
      - '<name>'
  logs:
    command: wire
    attributes:
      - 'services'
      - 'logs'
      - '<name>'

services:
  wns:
    log: '/var/log/wns.log'
    scripts:
      start:
        command: wire
        attributes:
          - 'wns'
          - 'start'
        # - '--lite'
          - '--daemon'
        # - '--procName'
        # - '<name>'
          - '--log-file'
          - '<logFile>'
        match: 'Executed block'
      status:
        command: wire
        attributes:
          - 'wns'
          - 'status'
      logs:
        command: wire
        attributes:
          - 'services'
          - 'logs'
          - '<name>'
          - '--log-file'
          - '<logFile>'
  ipfs:
    log: '/var/log/ipfs.log'
    scripts:
      start:
        command: wire
        attributes:
          - 'ipfs'
          - 'start'
          - '--daemon'
          - '--log-file'
          - '<logFile>'
  app-server:
    log: '/var/log/app-server.log'
    scripts:
      start:
        command: wire
        attributes:
          - 'app'
          - 'serve'
          - '--daemon'
          - '--port'
          - 5999
          - '--log-file'
          - '<logFile>'
  signal:
    log: '/var/log/signal.log'
    scripts:
      start:
        command: wire
        attributes:
          - 'signal'
          - 'start'
          - '--daemon'
          - '--asBootstrap'
          - '--log-file'
          - '<logFile>'
        match: 'SIGNAL_PROTOCOL_TOPIC'
  bot-factory:
    log: '/var/log/bot-factory.log'
    scripts:
      start:
        command: wire
        attributes:
          - 'bot'
          - 'factory'
          - 'start'
          - '--daemon'
          - '--log-file'
          - '<logFile>'
        match: 'bot-factory'
      status:
        command: wire
        attributes:
          - 'bot'
          - 'factory'
          - 'status'
