# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          scope: "@dxos"
      - run: git config --global user.email "npm@dxos.network"
      - run: git config --global user.name "DxOS"
      - run: yarn version --prerelease
      #- run: yarn
      #- run: CONFIG_FILE=./config/config-prod.yml yarn next build
      - run: cat /home/runner/work/_temp/.npmrc
      - run: yarn config set //registry.npmjs.org/:_authToken $NODE_AUTH_TOKEN
      - run: yarn config set scope "@dxos"
      - run: yarn config list 
      - run: yarn publish --access public
      - run: git push --follow-tags
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
