  
# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.1
      - uses: actions/setup-node@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          node-version: 12
          registry-url: https://registry.npmjs.org/
          scope: "@dxos"
      - run: | 
          git config --global user.email "npm@dxos.network"
          git config --global user.name "DxOS"
          yarn
          yarn build
          yarn lint
          # yarn test
          git reset --hard
          git clean -dfx
          yarn
          yarn version --prerelease
          CONFIG_FILE=./config/config-prod.yml yarn next build
          yarn publish --tag beta --access public
          git push --follow-tags
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
 
