  
# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          scope: "@dxos"
      - run: | 
          git config --global user.email "npm@dxos.network"
          git config --global user.name "DxOS"
          yarn version --prerelease
          #yarn
          #CONFIG_FILE=./config/config-prod.yml yarn next build
          cat /home/runner/work/_temp/.npmrc
          #yarn config set scope "@dxos"
          #yarn config set @dxos:registry https://registry.npmjs.org/
          #yarn config set //registry.npmjs.org/:_authToken $NODE_AUTH_TOKEN
          yarn config list
          yarn publish --access public
          git push --follow-tags
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
